GET http://localhost:3000/users

###
GET http://localhost:3000/index/645b099955be2ea01c14e7f7


###
POST http://localhost:3000/index
Content-Type: application/json

{
    "name": "manager"
}

###

DELETE http://localhost:3000/localhost:3000/645b099955be2ea01c14e7f7