GET http://localhost:3000/users

###
GET http://localhost:3000/645c55052cfe5e35e8b2ddeb


###
POST http://localhost:3000/index
Content-Type: application/json

{
    "name": "manager"
}

###

DELETE http://localhost:3000/645c55052cfe5e35e8b2ddeb